name: Sync from codeberg to github

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "33 3 * * 3"

jobs:
  mirror: # TODO: In future, test by running on containers - https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container
    runs-on: self-hosted #ubuntu-latest for github owned VMs.

    steps:
      - name: Checkout Codeberg repository
        run: |
          git clone https://codeberg.org/sdk/getBankDetailsFromIFSC
          cd getBankDetailsFromIFSC
        env:
          CODEBERG_TOKEN: ${{ secrets.CDBRG_TKN }} #add cdbrg to mirror IFSC repo to be sure

      - name: Push to GitHub
        run: |
          git remote add github https://thereadonly:${{ secrets.GTHB_TKN }}@github.com/thereadonly/getBankDetailsFromIFSC.git
          git push --mirror github
        working-directory: getBankDetailsFromIFSC # workdir makes it cleaner and reduces chances of error with cd
        env:
          GITHUB_TOKEN: ${{ secrets.GTHB_TKN }}

      - name: Cleanup for next run #Required for self-hosted runners unlike github hosts which are fresh.
        run: |
          cd ..
          rm -rf getBankDetailsFromIFSC
